### ISSUE TITLE
Add prettier-plugin-organize-imports

### ISSUE THREAD

**Issue by sgohlke** [dreamit-de/graphql-server#272]
We should add the eslint-plugin-simple-import-sort so the imports are sorted consistently over all projects.

EDIT:
We changed this to use prettier-plugin-organize-imports .

**Comment by Shinigami92** [comment]
I would recommend https://www.npmjs.com/package/prettier-plugin-organize-imports
If you like that, I can set it up

Prettier has the advantage over eslint of just formatting the file on save instead of showing a lint error and need to click / execute "fix"

**Comment by sgohlke** [comment]
> I would recommend https://www.npmjs.com/package/prettier-plugin-organize-imports If you like that, I can set it up
> 
> Prettier has the advantage over eslint of just formatting the file on save instead of showing a lint error and need to click / execute "fix"

Yes, it would be nice if you could create an MR so we can check it.
